### ISSUE TITLE
Can this plugin support CSS, HTML and javascript in html file?

### ISSUE THREAD

**Issue by qizhao-umbc** [alexmunteanu/vscode-toggle-block-comments#1]
Thanks for your work! I used to use Brackets and it can remove comment without selecting all the components . But I find it not working in VS Code. However, I find this plugin in VS Code and it worked in js file. Thank you! And I find that it can't work in CSS, HTML and javascript in html file. I wonder if this plugin can support them. Thanks!

**Comment by alexmunteanu** [comment]
Hey! I'm glad you find it useful!
I've included support for several other languages in [v1.1.0](https://github.com/alexmunteanu/vscode-toggle-block-comments/releases/tag/v1.1.0)

**Comment by cjaoude** [comment]
@alexmunteanu needs support for Blade (Laravel) files. Tnx. 

vscode identifier 'blade'

**Comment by alexmunteanu** [comment]
Added in [v1.2.0](https://github.com/alexmunteanu/vscode-toggle-block-comments/releases/tag/1.2.0)
