### ISSUE TITLE
Additional Languages support

### ISSUE THREAD

**Issue by jorgemxm** [alexmunteanu/vscode-toggle-block-comments#4]
Hi @alexmunteanu 

Would you consider updating this extension to include support for the languages mentioned below?

I could help by raising a Pull Request, however, I'm not sure if updating the "package.json" is enough given that the source code seems to be obfuscated. 

Other Languages that also use the `/* */` syntax for block comments are: (VS Code Language-Id)
- typescriptreact (.tsx files)
- go
- dart
- jsonc
- swift
- sql
- rust
- vue
- svelte 

This extension is really useful, thanks for publishing it.

**Comment by alexmunteanu** [comment]
Added in [1.3.0](https://github.com/alexmunteanu/vscode-toggle-block-comments/releases/tag/1.3.0).

I'm glad you like it, and yeah... modifying only the package.json wouldn't help.

Cheers!

**Comment by jorgemxm** [comment]
Thanks for the update, I appreciate it a lot.
Cheers
